# Generated by Django 6.0.7 on 2026-07-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="die_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="masters.dieprice",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="work_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
