# Generated by Django 6.0.1 on 2026-07-27 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_bill_die_price_bill_work_name"),
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="die_price",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="work_name",
        ),
        migrations.AddField(
            model_name="bill",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bill",
            name="final_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bill",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="bill",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ONLINE", "Online")],
                default="CASH",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("die_code", models.CharField(max_length=50)),
                ("work_name", models.CharField(max_length=150)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.bill",
                    ),
                ),
                (
                    "die_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="masters.dieprice",
                    ),
                ),
            ],
        ),
    ]
