# Generated by Django 6.0.1 on 2026-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(default="Nellore Die Cutting", max_length=150),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("gst_number", models.CharField(blank=True, default="", max_length=30)),
                (
                    "business_registration_number",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "logo",
                    models.FileField(blank=True, null=True, upload_to="settings/logo/"),
                ),
                (
                    "financial_year_start",
                    models.CharField(
                        choices=[
                            ("01 April", "01 April"),
                            ("01 January", "01 January"),
                            ("01 July", "01 July"),
                        ],
                        default="01 April",
                        max_length=20,
                    ),
                ),
                (
                    "default_payment_mode",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("ONLINE", "Online")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("INR", "INR (₹)")], default="INR", max_length=10
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("GRAM", "Gram (gm)")], default="GRAM", max_length=10
                    ),
                ),
                (
                    "weight_decimal_places",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        default=3,
                    ),
                ),
                (
                    "amount_decimal_places",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4")],
                        default=2,
                    ),
                ),
                ("show_discount", models.BooleanField(default=True)),
                (
                    "bill_paper_size",
                    models.CharField(
                        choices=[("80MM", "80mm Thermal"), ("58MM", "58mm Thermal")],
                        default="80MM",
                        max_length=10,
                    ),
                ),
                (
                    "token_paper_size",
                    models.CharField(
                        choices=[("80MM", "80mm Thermal"), ("58MM", "58mm Thermal")],
                        default="58MM",
                        max_length=10,
                    ),
                ),
                ("show_bill_header", models.BooleanField(default=True)),
                ("show_bill_footer", models.BooleanField(default=True)),
                ("bill_prefix", models.CharField(default="BILL", max_length=10)),
                ("token_prefix", models.CharField(default="TK", max_length=10)),
                ("low_weight_alert", models.BooleanField(default=True)),
                ("whatsapp_daily_summary", models.BooleanField(default=False)),
                ("backup_reminder", models.BooleanField(default=True)),
                ("bill_print_sound", models.BooleanField(default=True)),
                (
                    "auto_logout_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (15, "15 Minutes"),
                            (30, "30 Minutes"),
                            (60, "60 Minutes"),
                            (120, "120 Minutes"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "entries_per_page",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "10"), (25, "25"), (50, "50"), (100, "100")],
                        default=10,
                    ),
                ),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[("LIGHT", "Light"), ("DARK", "Dark")],
                        default="LIGHT",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "English")], default="EN", max_length=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
