# Generated by Django 6.0.1 on 2026-07-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="allow_manual_weight_entry",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="machine_baud_rate",
            field=models.PositiveIntegerField(
                choices=[(9600, "9600"), (19200, "19200"), (38400, "38400")],
                default=9600,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="machine_data_bits",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="machine_parity",
            field=models.CharField(
                choices=[("NONE", "None"), ("EVEN", "Even"), ("ODD", "Odd")],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="machine_port",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="machine_read_timeout_ms",
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="machine_stable_read_count",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="machine_stop_bits",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="weighing_machine_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
