# Generated by Django 6.0.1 on 2026-08-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_systemsettings_allow_manual_weight_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="token_prefix",
            field=models.CharField(default="T", max_length=10),
        ),
    ]
