# Generated by Django 6.0.1 on 2026-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0003_alter_systemsettings_token_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="token_prefix",
            field=models.CharField(default="TK", max_length=10),
        ),
    ]
