# Generated by Django 6.0.7 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="staff_edit_unlocked",
            field=models.BooleanField(default=False),
        ),
    ]