# Generated by Django 6.0.7 on 2026-07-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tokens",
                to="customers.customer",
            ),
        ),
    ]
